---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --production --audit-level=moderate

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  - name: coverage
    image: node:12
    commands:
      - npm run coverage

  - name: build
    image: node:12
    commands:
      - npm run build

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-record-import-transformer-publication-archives
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: QTz9ATJUON7LrSDJ9Z/llLTGIRheoW9K7azMLkLlPoyKKrD6FGD8Bdd5ACUzb1xhnsM=
---
kind: secret
name: docker_password
data: SgZvOI3pZ0byWf9qAdmJkNcjGJzZXXx6PamlqbAzy3gWfxQ2eFFkZlmuAzZ67V+vBj6u23c2Ugjz+dFf9Ptbv5zdUoPumuAk3Ha03T68H5Fw4Izy2N4OkCwq4So=
---
kind: secret
name: ssh_key
data: M1+dWKbUUyvgD3G0CLFG2gf2DBVC2UDLAIXy/4Sz7fbr+AtjXZLxZsYTpwYTgSDH3dSXUWJK9tCQ8Nr8Mw1Ean2qxl1gkAlI3/GHhy4Nb3saZYlM24uloWQhY/dlOMr6pqfjlFDZlBerZRLtsnIcARTEzgHIGuolC9kRhL8RGExUESGnLAdFQ3BIXacELVWRR2aC6t4LLppCqwhXUREbau81DIazAuOu5trvdJXdw+zdLxuQpzczVIXQ/94MIlx3+GNkAb09bjXHarZdObjMbJMNvPzk00Omxm9m7UAacwmf+vD9N/IAlVrhehu9QYhuTF274NXWsx9NI9b0HaeO+r6PTvzKbcX5fGrQI/nDQCQ5P9a7fDYiMxHkR8YkxoSeyinzOwHcCBNVQjxS5Afsighojp0j+6N1KMSswL1TequZNVI07qFQGMjd9WO1NJXxJLe9zRKfIM/pS1n5vi1yWPKJwNAEqToX8JkgR/cB4pMOW7YoN+KnhXXYKb4YvOb5nMBIfAhEpotJR1/Y9Ic2uUe4Qs0+i/zFCaFYk2GmqbbMpCC/fykGeVMNs2cdo3oMJubNHhsud1gnErFrNzie1lXV6I2tW/cTJ9CzA1tz3iA8bUB9MTbUk495xtvWqp7ojd91HbYvtbStN0DbSFIPbEa4PmODxIVhneQCapYiblCFVtRbgyEUSJQmyUEPpG5yMMlS7P5qs0/kFCuSzmiBEBj3Z3Bsi/7gL/vWnYmA+14X2D/k8b4Ux1AL/0MyxGownHfNAF7MyhZIqKZNPuinaOfR0y3VmJANTbGLFMFts8Y/tpcKDJKm+Dhc7SFD+9VbWQjm8yFXVJ5ADWW+c1t+xSzsKEC+MbMEbH9Lqij1bl1pBcnQNrP5+U8Gfm0td1xcW0oaw/F2RPb/i/hJmqysaVlvB15BSaqwN2a+JuJbM3Q2WLMQEMhqOsKWEFe7ayWVR3NrMsGch2/48R6paXhl/RJWN9NHnQ/dBZhJcgYpxi43/YJ3bqo65ERxq4n/gCjH/M4RralQm/noEopElxWThxjGdd2HHcut6318P3mluHYgBmekYqeyMheyLGQrDveeLknZ9q/zvrCAv78LS0K07A3EhNYsu2AtpIQFDpgW6wVHZ82aF165t/GgTV/vYutY2/E8RRmKgwueGO2z1tt82SASig9V+3L2eu+GfWi/Fmzhv9jxrHo3AvDpT4ZbQgjok35hsD0IsCvkuFVRJeI8dgNotwvroLCh7mRLes1vxlYmOzlNRtsu6W+VPvpn/ODYOeQsyX0VnVFfTvShDS32GZKITaok7DLl7dTJuXW/+x/jXqWV5n2NNcRBiT3kiQFS1c1o9cOGeKBjI0kCfLt+na/mqxMnPuIjrf+a+3jkMjGM87JYK1Ey1zD7j81IJoaoYXKA6tS3+/n4C2geObKFzA7JdmNnpCkmcv5mBz2uyChGc8Z4UbxxPSTS5p0VaXaG5ttqe+UgBfxT97Yybw+jnIqhdsgkWllfQiPB87SxUvguj6qt8PKGn2io+2qPI9NFlEUL7v0lOu0pc2t2S3Pky/7gYI8JeSHuqAFenyG2HfdzTrTLPepmTHunse6iTpMNyu2leBmoK+bZtVaM32RGRHP5crm2lNosI5cBBnBNBKF/mkpmZrbBWmxPWyj8jJ6l2JhMhKnQhD0nCjeZkIpxuCawcFRxcIAesvAn534vJIyF4Ep6I5OwKQDClzlu4MYbB54l42SWcy3hIB1MM7UkZgOWq/+aCJcgEF2yTacDeV0ORUqMm7SeCubPWM29ZCmIgyzyX69ipuqmj7gEvYzE03e1oJFWUxbCBQ7MaE0W7dLB6a/UiLAlWi7IHyKsHWvRT4jIH3DCTJH3cWM6tFYfSH05yxQ5V5gCSa3xxle1IPhyyVPJbfpOicbh5c8Yv2MQ8r/hVJvnb2CdTX4AoqbFj+o6N6XHTd2Qa/lMY+Dtw3IW3DZxfznKG4Fbdc7+2niuRjLawnCotp0eZcSn+KjycIv4YmhO7xQ6FmsOpVlExOxB35CMCYIbzkZXzUqHOz0ht5sfXvOo97eLNYAutDXl06+5g5WpC1Aar1HnaVdALfyN356VpWFyETX0/DsU/c4EFIT9WYfp6OFjmi5htDsTYVNHgDKGslGc3OFAyKAuavYZ3//VDNHQF5po9jZoGeIktsJSWIVjsPsHLtaOJeq5f+L5iZ9Fqm5LXHxFpWV6CAFrBOWC82sDfZxZXrfoGFvkqFfoZe1y8gZarFKKsMgySz5rShtOd7IVvfExa3dH2q5tHHzfi2Z9arMMz33vuzpxUw3m2rZ6C/+ekgvBblmq8EOaLalWFqQMbnt5UWBMbJ1P2HKEvK5Uwnx7gpx/7VuW0va9CH1RNlwbA1RXlYvNEe57qT3LTjwa+wl36qDLuVd7kXeGvZoP0t4oYh2DxS6sUGLE66iCakct41UTBQ52kb55zNWkw7mPBWOfYYxYPvisWdN6zsToNP8aXjnDlkM1+gOIwwNi7bGBjkF5u8YbzK47AaIxXkM6eNx+oZYBv0OVYeZGsJHKIfWhaOfwMIFkW/sn7/cMCbZsdp5W7inRfbFiZASvzGybWZCcQMR7AwjdMF9AhVjWFi6leQk6osHdi7pfL2HmZoa5PucKmWgWMRzupwkdyvXzBWmAEq2H0oXt09EJmf/gonDVstqLAkw27WYYB037M0z5O72l/+AeTB8eXbOqSgMI8F4mX9AnrwS+4l5lRO1qxjLfjChqF1WPHxU1tdEKY1hNs21F425+as3X/I6Sj0l55+IqnR6hihGMRfKnkh1gSDlI9LYOVd/VMnk1uUHYCkYfB/ZkxaozL3O+wsS321pmSRGNu1tjWuV8Ihw1GXlaXyfyotE3SB8GO/sofeXzXYf3cN0MXv2zWQGGXPno6rfC6UjzqJLI2yPf4YTt9E5OkRvPjA7JHk4NUaz+uYKvMGylIgdrwOGGyqXb2K7ZpeX+SGMKCa105MEJmOBSaInX834pehY0T7okREsvam6Nxm1Dki+j
---
kind: secret
name: gpg_key
data: TjDRyd1hmv4D3an700Er2sdEScM59ctrpyMUyg6vzykWnXiTQATg68HYGkQYGxa+1XM1Um9QgkEppmweslcNYM262Og2PxP6XSNzVhHCGDl5ui4wOlSeTCvkjnD4eZMFAJlJ2bhxqQVM24rFw04re05wEx1e5SelP5jSI4aa5yrlh4nCLpEimIHrlMuaiC/3uVdI6RpBOv8xeiicUZIlwZuWa5dkAQcMKb6cczEpP8M2slcBC8WodcLnhcvBT4cRsjSdE8AjCJtX9GoOl8nibUVaJA+tGGy1mdUpbER8r/0nuHFv7uWw7iKJWgOUsVDH0HNP2zNFPnbGwtkS9MGPGInXvF7Jy4cku/JW8QBSbsNYHmwQAZtZvdvwtCIoF7+AquQzw++dEHPcYNydhqRM4miFrESwYTdJdMivGs9P+C94PxjP+dNH1TaHkAay36k3wTzCotTXY0KL19gibZLuoxFItaGRFfbMakpc1B8TLXaYlrTADOgKxDPngOpfnZgp9rtLH9WGmp22EJmbYYxC/jBZY1NO3GzX60iT62rq7Zjq7Bz0mFqfe0TVFn+1bA42Imp26dNT1xNCplxGszwl5ji+D891+G1T8Wd+GYftpC6U/5Tys97gYoVPgHBu0ZLhDNXaG96nihsgX2ihIu3ihxochyM1d3LMw8fbAIMHpkZTuv/JvDja9zL4aoBZWxmvzv9Tp/KIaE8mVYSb/h9/9jaHI6oe+t1B+izM+9LPGsgadmxg+sTTHzhpsAwfbxOzvIX0m0mZ/gDZsP5nohvnoKoaj98ZifdngxC26I60bUlzfy6bLdvYCT6K6E8TqHdZbXwsOrss61L8SpdNstZF8uvUBKIQv94Y860iKFR+7j9NDsqeUMDBqlHXPY8WORj424B4GaN/bTq+GgveV5TnJ0/Ic2uMEhjMRClAv4Pxuk71RyeeAxnY+z+lQofViXTY+IHGL66bekqk3RqSOOQnYEmjijnuZsIiy3IkH+B1DUzxsVTACY5lN9gy+mKmevT8nJ3fSrz4R6eDY4dzH/clSVPDECnjL5O79+rbq/ZcQ1Z5NVMz4xExlAr5ByPV7RjPTskv+PXKBAvGF7rklgA+aNjGbPFtMye7nBcnHLKDuFkomj3byUjNbPMSFBsmbQMo6DYEGGve23X62euYYaIYJqrd6FlSxyIW/MVYLwk1EGCAbLR0s/e/PpR2jsgnuDmRri4v3TZhqAviN0NG5D9gXfkWdflti3nDoCfJ+KKLYpy9RCib8ip8+sYmExRxK8VvQPvvSpIl6tLImvy8QrYKyJl2OiU/2a3O6bcrJHFqY4mgg9PWaAzFhpqxwdUtES5N4rRJlTat+XJtkNO9pSy+fSLD7ra+hj4i1DpaZhUAxJlo884S9oGj7ztGaSbHzQMqXR22eRq6Db+Elz8wLTkXrUNuox9ONK1f5Ovm4c8SQrTZgfUaSe8PiLti6+eJHsIedFFLrb9dyKbNw3i7rX3Y2D9b9yBdZCv1MoDhyiPjqxLDSVwQXzkfdLSkhbjAYNwCrzaoyEcejxoretD1LTQFihW1y6EJTkOQ8Yp2Fylchvfxpc4gRpXybzmWftocudFeqejfOG5GevP87Un6U511NRFUFSRwnq02i+SyjMoIApyPC5fKpVQtsIoVcZUWR5K/F7QV+2W6PyGWNcQrDvleYEYejJSn/Df9O1fGoNbRUR6Zcq0AcbQwWvGqOkPxW27XIk026wJxBii2n/DW+1Wo6qpEqsTmktjCcmjnWxGWhF10BAxfVdV8CI0WPo1Eefmk2i+JcKh+p8/GktOntoLXta87Be1ZgQKhAZ4uhGyQyNcqZYYtnsD89RCZJ3lvij73ljFx1fwLDQUSZi168gNlY3oe7JMkT3oC0y/3kF/EKtVVS5oebrEOcL4wZZ2A7VKCzjJBTl77FigdoWfvmzMb8qcLH4pdyAg3mc9a8S19mke6z9qAum/yXuwYwICALTLE+V74/crUmck/1L986EmPV9jp8p1WX+e4VGcsSEw4rqclGNxPZhraNLPCRxVWi6ItppJhrwNNjxm8k2fFPKOL05P1GoFOYciLZKqrZGrFQQ8GvRBSjCrJaE6y/1cjGFaguUXqgbpQ6uwcwnipNJflh3SoRBHSao/ebjZbwo33vm4FL8BS5UI9iJexYkZyRiS2HwI7euk3baqulRUQkYwLDYFSWDUyJAa69TC+Fv1KTrAoB1UUBEARVoIj+V1X/m6uECOAF+UtLFG7ORK1thhjpYxa/9k7PlEOA5GUYOXC7hSpYvJpbmic/WOgGqS7Ms4cnbKarQ24JTCcJHSke8hk4g0gC5E4RlOhxdOmMYOE2jjWbdBdEfdgsAkW9WElO1GBSMDSatys6uGRy9uwKKcWdhyyH7cPNs+TvznvXFDeDJU0ysqUUCIX2J/aClBMrecPXCMD3KaWNB+gkp+3Hk4U1qo9u+r85s2tqylU85eWhhmQbha6d7tr8tpG30GXxcOaThmC7KCZMvojHpHGv4iyxcrjsBQPDG52oK7uvj0V6x0iUN9B4SRs1d1FumcpDnTdSRJ+rfnIZLGyAWUiYG6mh3hU0PSEuF85yU8vHROZ0rwIAZlsyAgTUN/t/2PVxK2CWwJm4muWPWbVyaxvNrvrfiujiZc8oF0OumSO+988E158dzyzIPvTM4UPbWypZGKRadyYsMpBBUorqfZJYNK4tPFzE/wrqoO9vGnbgaFnTizYdPgy1/z1iHvGKA3sQLuuQDxajRfnsA6M+mWhiTlDkWh68+BJ4mz69L5pAoQc3uqN1dl09bl574ijUKa7GXRFbgmO1ZE1P3L93tLTj5N5DL7Kzkv4AXIEpCDSlhb8SOxpdPdhMYf6XzhQSK3o+b1HKR15pxR84j6U6S/dmUgmx5y6O3DNxevD7ho505WtIm7BJmKIZdi0Z5MkBzoPpYyk8xHzdhaIBp15KVC6T33Y33wGE+1tCKhHK0EFR8oCPEUdZmXIuoJ5Vojo+Lb8sHzKedYioojNUN/lbejfX2dJDIH1XDz/uDIhEnKgEKoIbkO5Pgsf/xveWMXnFJFEoybFxSn9Mh+Ac86k181CLi+5NvmsYru4AwaR/xquIrWHBh+jcF2boq4kWVOaiA2aVzbodP3dykTPIry8xlKrPXu5/VqzsWJRJQsnLYfeH9QFVOzXC1Qt0fnRnAerTVJHe4XFj7JtLsG81lLnsCk1LBrIUl2lQvNttv/GadlSQbFWqyPMUrd5c9iFy2ET1ZKjTF+I8gxI3xYrfG5glzDMq9u6+rv1cyTRj08CHlKpnFQVUojRC9ysMWDFNOUu0JC7OwMSoqYno3o77wxbzKKddNNi6UjOuf2iuYDOUaU8YP3BtupN1t9xbtZzNbF6bWQdZq36SA3J3hINzRBVVO0yUsykYRpP1N0c2QMiFz/lDazujPofjSwtZ8ah1YwcrNAC5+4QS71+yjLqiz4OmXNwlGZ2alDL909BKmlsBE1j7yWO495tjBjOwx4Rtm/Wgi4qfFu8UMQYiqALgy4HSAqR0KrZBjtQ+O2wLWbtj4qRsT/SeLfD12/WWiv+22CcDNw9SrKF6zFckysw81SZ3I4lADF1bVfgykmSghIbBAikTNO1PebK0ABX7Q+FfagaR65U7tGeJUM/6nfpvo2DgXBHjH5LQa2oYYz8kcXPPWe93JQ8V205Pu13sKLdKu4tKp5dCAVrTmP8ZPbNu8wb1V61xJQwadaIxN02z6enwU499mymeP0epP8FBx0z6PSGCKhcFy2uVbBZkHIc6J6Vt2lNWCbvTcM+mozcfVOXFov0JYbcP50jdOydTrESeANIoz6PPbRRp0qFqwCl3v8MHOZdmTvPZ9aohFBgj9bpayMmlLoivmy4jf7YPDWQTn7Uml7oNoCwzCVqSbpzyssx7eDXgTrUGkWXk8ncBzWl2KnitGZnyu0k0ddzEgQbU/f8UfOdE8MQHQJowbUbXyvD37V1QtDc+UtbbJzO7piH6ofJVQMjMjQJtvPO6dGgHBqn7OVafUfJQjAMpQdsiYfTwF0mauM5TeXHvd4nCGGmhI9YVSiPbqgBc8uFKkrep4D/1/2qMquMZtMWEqHZ64TEYakD+SdMaXLUK18NoWXBmECQpuEpxljI71+YQ+7j4xu1tOx+F+qtp+Od5V0gQtifJxjbWMk7g8/Hb+RTkQIUB1l1PUl+QZNC8x4GG0Iy8X6O0v/bkMjYLzFiVhidQraO1lKHXHOkuOGed7KK1NcLQOzs0tDVzk6Y5p+iRx6cHtm6+9q33dcYlt5KV8dL5VOmj1xoYcII2RAmAJAFuaErdf0xVQ/RAq+xfH8/CF0BHRK+GApuDaUnvXkXG/sv2C6WYE/yHt8jyvKnNFlAiwkcb+xfHtVApwCUn6vDq3Qbu1eLvOzTE1D9vJfWtWgb7JD2IymZ0ODQgxTugoKxS29PNaiwWMjih3IYBWOwh76DC+Q+rHf+0LRfdwqqKq1k8jfvYyQGnjYu5cJG/DtuI0oHGQNdNeCSMO2USeA4+v8Y1kHkFCFjv+w0KrMi0RK3bGvVz/oA715ZGVnhvSlrbEEEDRfLhavQZFuZ7AThujqUb33Pi/afItGwFO49895/0xwia4xlaM+C0YiUW3gyGJOrcESZ+erMtQ1sJ1XrcN2JB5r4Dwwb9QIo2SH76ajqwPLl9a32rMFiFoE8P9DrUoCJEov81ksjdD2SjBThqjbLQ/9P41PnJ5ME2izk2AhGKafQNwxky8+dYpSRC0266MLwatmsjy2DZt5idR0aPIgZxa5Zjay8YW1AQLAPmKO+FkZ1DOk+Ja0PxA23DsuEWUFBn9Sg1Bd5nEUayCxIOXXvriJjGldCYpwOIGZ2ZLHXQtId9urJimHK28rB2f2hLYLRh44cmyrqzgTyqCbHp5GtfcHfydyGBK+wLW0ZSZ1OxEYl6rlfpA1jAPXpagLsdIT4YoCSWzfBr/P2ZLwLQSv5fEXTZfzhVb4Q8QJp6n34GJAjbc4EzPRB4cggVCGLgk3uaUgBS57fOARaYULn5KIe20B4lx0ESu9kSmIKDwFHFBjLNB52MBNhDpTpgmkA2LljRWOQVPHyQv5pK7eRDuyKKQtPHqvvRd7y218AYS946PRb2kZclJsYEeqZ4jih0VQ6lf/H5BypjMoEgi7zDjEnDl/ZhHaZfIHQSgyLxY0m8jSr2CGxAMtpHP0jHDJLePYmq6G1F+5gR6rP4DMeWmlR1iSoyvtOXAmhKcYVNiTn5fJF99VzELiU6oWqrQwcWugmEH+/acCyPLSv4rOgzmkJu4Rgt9EMgf2BVqPmRewsRLX5xtuV/kH3QhNyPKROgt6gPhMdbk/Kq+HQG/na9+urnizgQf8ZQZGJEQnApnSh7qTbfC1y0A2aljf9jZ2OFPy0g7Guv9dh0cbIwHdIbGPARx/b3NRDFLWsRma7WycmeszJsxt0UAlXThZOPXJc4TGwYMXuNqp9b3J3Hbp6Q5LyJLShWEye92bGaplp9K9H/HJqOjEBasp0pffzDtk+s+G1SwU2OGkcIVvlCSkBdM/fdsVTMbZdveibjbKNDtgYzqg+2RTbtLiZdm0+4gIj4esc+suppDvX9wede3bLZCsJf15XHhXRr3z6kQ6PWyxky/Lk9Hf8BwxPy1ewqWuZBhENnPVYNrlPdJYOFRcOUgYuzbhRFm/6vfCoO2LDKz/0Jof63pTZ3rj4vWS5F4jvhBTF5J17puQosoySIHiPI9Hy7uU4DCxNLqRXJAojU88hdLgEeNR5HNgRmmy+sMuHc2k65dSQyQN4UVYrpg77iCqSxSNLqIrIyuJ0JsjT0/wY7W26AEFgK4J1/+UlM73U7e2xbIy1BleelDxretZBRdbCNATAUUG1ZC6zW/XTCqW+EXsxtgGoTB0HkN9oO4mcydDQmfi295AWpa9ghJsfO8PXGRDEp2aB+7Rokb0RlgZ8N6La/TcxfpLgd3atsjtFhhD1q9lg4oop1GBIiI1OctgcsN6vbXcTdOONdnHNhl4laoZA4eGKT/lpIEJCnzyk8OO77k7ntHCCTDzqvQod2rVrjcpokPnu//wvkxpPnVGr6KBRREX24g5X7iJjUZ+qFhqAQiTfd2AkcI7f+3PBfJVxiY3VIhu1QbUdQ7cN3HGV9PqsFtvgSoWr0ZmZFrw25OY1y8LtYWIyp39mpkbsZMceitLY5btjsxpBVpLzlYljQ811Ls86QnaGi7lcSezTlVWCA7RQs7cTelRgkCEXeh3kpaLg1mkXXyoh2iENpMG8Rk/RzYjrm9jdfBAPBZErCQ3Q6KneODB5erPjiPNQYkNaDegrZ7ZhLrwfEYANQwqx38suPcHMyBESEx22+fA4rJXrRYK153M653mCPG+ShKNBfrVDO/KcNAg38qgQ6JtCvDoFykNbDLJqArJsYtsvYCXiyrJsivaTV4GbpFReyycJM0dpyIUgG96VJ19bRAHQxlSmlaLCNrSrzRDSoTIJRTk5btWgjPG3zeEFCz9CPvfSGQbIW2viHH7kLxn3m7MrxcvfcwP3eOh5pZl8vVBLJL7rGv3YliHnTHe4GQRlP/h9XMigEWptM4hRhdYOgE7tYG9fgUu7LTwd1R7YCH/qyfAJRRt+WOlfh/GnLsDv/tqaav0MjC9tqaVFDIfT2jF6zrFWmHrla4oymVMYA7j9xlRQTdg5vg5OfQp3xcNnZv+rfw==
---
kind: signature
hmac: 3c11fc6dcbb98ba423ee553cef034a9966ab8a9f723219cb3b9852a931de815f

...
