kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node  
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-transformer-publication-archives
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: QTz9ATJUON7LrSDJ9Z/llLTGIRheoW9K7azMLkLlPoyKKrD6FGD8Bdd5ACUzb1xhnsM=
---
kind: secret
name: docker_password
data: SgZvOI3pZ0byWf9qAdmJkNcjGJzZXXx6PamlqbAzy3gWfxQ2eFFkZlmuAzZ67V+vBj6u23c2Ugjz+dFf9Ptbv5zdUoPumuAk3Ha03T68H5Fw4Izy2N4OkCwq4So=
