# KB node pipeline
name: KB node pipeline

on: push

jobs:
  build-node-versions:
    name: Node version matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NPM_CONFIG_IGNORE_SCRIPTS: true
    - run: npm audit --package-lock-only --production --audit-level=high
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present

  license-scan:
    name: License compliance check
    runs-on: ubuntu-latest
    # container: docker://node:22

    steps:
      - uses: actions/checkout@v5
      - uses: mikaelvesavuori/license-compliance-action@v1
        with:
          exclude_pattern: /^@natlibfi/

  njsscan:
    name: Njsscan check
    runs-on: ubuntu-latest
    # container: docker://node:22

    steps:
    - name: Checkout the code
      uses: actions/checkout@v5
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@v9
      with:
        args: '.'

  openshift-webhook:
    name: OpenShift webhook for image builder
    needs: [build-node-versions, njsscan]
    runs-on: ubuntu-latest

    steps:
      - name: Staging webhook
        uses: joelwmale/webhook-action@master
        if: github.ref == 'refs/heads/test'
        with:
          url: ${{ secrets.WEBHOOK_URL_TEST }}
          body: '{}'
      - name: Production webhook
        uses: joelwmale/webhook-action@master
        if: github.ref == 'refs/heads/main'
        with:
          url: ${{ secrets.WEBHOOK_URL_PROD }}
          body: '{}'
